# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build docs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
        
    steps:
    - uses: actions/checkout@v2
      with:
        path: actual-docs
    - uses: actions/checkout@v2
      with:
        repository: pedroaraujoOS/docs-builder
        path: docs-builder
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      working-directory: docs-builder
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Copy docs
      run: |
        pwd
        ls
        mv actual-docs docs-builder/docs
      working-directory: $GITHUB_WORKSPACE
    - name: Build docs
      run: python3.8 build.py
      working-directory: docs-builder
